import { useMemo, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useSearchParams } from 'react-router-dom'
import { Activity, ArrowUpRight, Check, ChevronDown, ChevronUp, CircleAlert, CircleCheck, Clock3, Filter, Gauge, GitBranch, Layers3, Plus, RotateCw, Search, ShieldCheck, SlidersHorizontal, Sparkles, Users, X } from 'lucide-react'
import { api } from '../lib/api'
import type { DifficultyClass, DifficultyRow, GovernanceStatus, GovernanceWaiver, LedgerAuditRow, QuestionBankRow, ASMLibraryRow, Tier } from '../types'
import { Badge, Button, Card, ProgressBar, Skeleton } from '../components/ui'

type View = 'overview' | 'questions' | 'asm' | 'waivers' | 'difficulty' | 'ledger'
type SortDirection = 'asc' | 'desc'

const viewLabels: Record<View, string> = { overview: 'Cohort overview', questions: 'Question bank', asm: 'ASM library', waivers: 'Waiver requests', difficulty: 'Difficulty engine', ledger: 'Ledger audit' }
const tabs: { id: View; label: string; icon: typeof Users }[] = [
  { id: 'overview', label: 'Executive view', icon: Activity },
  { id: 'questions', label: 'Question bank', icon: Layers3 },
  { id: 'asm', label: 'ASM library', icon: GitBranch },
  { id: 'waivers', label: 'Waiver requests', icon: ShieldCheck },
  { id: 'difficulty', label: 'Difficulty engine', icon: Gauge },
  { id: 'ledger', label: 'Ledger audit', icon: Clock3 },
]

export function CommitteePortal() {
  const [params, setParams] = useSearchParams()
  const rawView = params.get('view') as View | null
  const view: View = rawView && rawView in viewLabels ? rawView : 'overview'
  const setView = (next: View) => setParams(next === 'overview' ? {} : { view: next })
  const overview = useQuery({ queryKey: ['committee-overview'], queryFn: api.committeeOverview })
  const questions = useQuery({ queryKey: ['committee-question-bank'], queryFn: api.questionBank, enabled: view === 'questions' })
  const asm = useQuery({ queryKey: ['committee-asm-library'], queryFn: api.asmLibrary, enabled: view === 'asm' })
  const waivers = useQuery({ queryKey: ['committee-waivers'], queryFn: api.governanceWaivers, enabled: view === 'waivers' })
  const difficulty = useQuery({ queryKey: ['committee-difficulty'], queryFn: api.difficultyEngine, enabled: view === 'difficulty' })
  const ledger = useQuery({ queryKey: ['committee-ledger'], queryFn: api.ledgerAudit, enabled: view === 'ledger' })
  const queryClient = useQueryClient()
  const [notice, setNotice] = useState('')

  async function runAction(area: string, id: string, action: string) {
    await api.updateGovernance(area, id, action)
    setNotice(`${action.replace('-', ' ')} recorded in the governance log`)
    await Promise.all([queryClient.invalidateQueries({ queryKey: ['committee-overview'] }), queryClient.invalidateQueries({ queryKey: [`committee-${area}`] })])
    window.setTimeout(() => setNotice(''), 2800)
  }

  return <div className="space-y-6">
    <div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between">
      <div><div className="mb-3 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.18em] text-emerald-700"><span className="h-2 w-2 rounded-full bg-emerald-500" /> Engineering excellence control center</div><h1 className="text-2xl font-bold tracking-tight text-slate-950 md:text-3xl">{viewLabels[view]}</h1><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500">Standards, decisions, and audit signals for the ASCEND engineering talent system.</p></div>
      <div className="flex items-center gap-2"><span className="hidden text-[11px] font-semibold text-slate-400 sm:inline">Last synchronized 4 min ago</span><Button variant="outline" onClick={() => queryClient.invalidateQueries({ queryKey: ['committee-overview'] })}><RotateCw size={14} />Refresh</Button><Button><Plus size={14} />Create control item</Button></div>
    </div>
    {notice && <div className="flex items-center gap-2 rounded-md border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs font-semibold text-emerald-800"><CircleCheck size={15} />{notice}</div>}
    <div className="flex gap-1 overflow-x-auto border-b border-slate-200 pb-px">{tabs.map((tab) => <button key={tab.id} onClick={() => setView(tab.id)} className={`flex shrink-0 items-center gap-2 border-b-2 px-3 py-3 text-xs font-bold transition-colors ${view === tab.id ? 'border-emerald-600 text-emerald-700' : 'border-transparent text-slate-400 hover:text-slate-700'}`}><tab.icon size={15} />{tab.label}</button>)}</div>
    {view === 'overview' && <Overview data={overview.data} isLoading={overview.isLoading} onOpen={setView} />}
    {view === 'questions' && <QuestionBank rows={questions.data || []} isLoading={questions.isLoading} onAction={runAction} />}
    {view === 'asm' && <ASMLibrary rows={asm.data || []} isLoading={asm.isLoading} onAction={runAction} />}
    {view === 'waivers' && <WaiverRequests rows={waivers.data || []} isLoading={waivers.isLoading} onAction={runAction} />}
    {view === 'difficulty' && <DifficultyEngine rows={difficulty.data || []} isLoading={difficulty.isLoading} onAction={runAction} />}
    {view === 'ledger' && <LedgerAudit rows={ledger.data || []} isLoading={ledger.isLoading} />}
  </div>
}

function Overview({ data, isLoading, onOpen }: { data: ReturnType<typeof api.committeeOverview> extends Promise<infer T> ? T | undefined : never; isLoading: boolean; onOpen: (view: View) => void }) {
  if (isLoading || !data) return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 8 }).map((_, index) => <Skeleton key={index} className="h-28" />)}</div>
  const metrics = [{ label: 'Total associates', value: data.total_associates, detail: 'Across active cohorts', icon: Users, tone: 'blue' }, { label: 'Assessment progress', value: `${data.assessment_progress}%`, detail: 'Course gates completed', icon: Check, tone: 'emerald' }, { label: 'ASM completion', value: `${data.asm_completion}%`, detail: 'Milestones cleared', icon: GitBranch, tone: 'teal' }, { label: 'At risk', value: data.at_risk, detail: 'Needs intervention', icon: CircleAlert, tone: 'amber' }, { label: 'Pending waivers', value: data.pending_waivers, detail: 'Committee action', icon: ShieldCheck, tone: 'orange' }, { label: 'Commission ready', value: data.commission_ready, detail: 'Ready for sponsor review', icon: CircleCheck, tone: 'navy' }]
  return <div className="space-y-6"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{metrics.map((metric) => <MetricCard key={metric.label} {...metric} />)}</div><div className="grid gap-6 xl:grid-cols-[1fr_1.15fr]"><Card className="overflow-hidden"><SectionHeader title="Pathway distribution" subtitle="Active associate mix by engineering discipline" action="Review pathways" onClick={() => onOpen('questions')} /><div className="space-y-5 p-5">{data.pathway_distribution.map((item) => <div key={item.label}><div className="mb-2 flex justify-between text-xs"><span className="font-semibold text-slate-700">{item.label}</span><span className="font-bold text-slate-900">{item.value}%</span></div><ProgressBar value={item.value / 100} color={item.color} /></div>)}</div><div className="border-t border-slate-100 bg-slate-50 px-5 py-3 text-[11px] text-slate-500">Distribution is calculated from current declared pathways.</div></Card><Card className="overflow-hidden"><SectionHeader title="Governance activity" subtitle="Recent decisions and control changes" action="View audit" onClick={() => onOpen('ledger')} /><div className="divide-y divide-slate-100">{data.audit_events.map((event) => <div key={event.title} className="flex gap-3 px-5 py-4"><span className={`mt-1.5 h-2 w-2 shrink-0 rounded-full ${event.tone}`} /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><p className="text-xs font-bold text-slate-800">{event.title}</p><span className="shrink-0 text-[10px] text-slate-400">{event.time}</span></div><p className="mt-1 text-[11px] leading-5 text-slate-500">{event.detail}</p></div></div>)}</div></Card></div><div className="grid gap-4 md:grid-cols-3"><DecisionCard title="Question quality" value="94%" detail="Live samples passing quality checks" action="Open question bank" onClick={() => onOpen('questions')} /><DecisionCard title="Waiver queue" value={`${data.pending_waivers} open`} detail="Decisions are due before next cohort gate" action="Review requests" onClick={() => onOpen('waivers')} /><DecisionCard title="Difficulty calibration" value="Balanced" detail="2 courses flagged for committee calibration" action="Open engine" onClick={() => onOpen('difficulty')} /></div></div>
}

function QuestionBank({ rows, isLoading, onAction }: TableProps<QuestionBankRow>) { const [search, setSearch] = useState(''); const filtered = rows.filter((row) => `${row.course} ${row.tier}`.toLowerCase().includes(search.toLowerCase())); return <GovernanceTable title="Question bank maintenance" subtitle="Control coverage, rotation, and live sample health by course tier." search={search} setSearch={setSearch} filters="All tiers" isLoading={isLoading} headers={['Course / tier', 'Questions', 'Coverage', 'Pass rate', 'Last rotation', 'Live sample', 'Actions']} rows={filtered.map((row) => <tr key={row.id}><td><div className="font-bold text-slate-800">{row.course}</div><div className="mt-1 text-[10px] uppercase tracking-wide text-slate-400">{row.tier} tier</div></td><td className="font-semibold">{row.question_count}</td><td><ValueBar value={row.coverage} /></td><td><span className={row.pass_rate >= 80 ? 'text-emerald-700' : 'text-amber-700'}>{row.pass_rate}%</span></td><td className="text-slate-500">{row.last_rotation}</td><td><StatusBadge status={row.live_sample_status} /></td><td><ActionButtons actions={[['Edit', 'edit'], ['Rotate', 'rotate'], row.status === 'DEACTIVATED' ? ['Activate', 'activate'] : ['Deactivate', 'deactivate']]} onAction={(action) => onAction('question-bank', row.id, action)} /></td></tr>)} empty="No question bank controls match this search." /> }
function ASMLibrary({ rows, isLoading, onAction }: TableProps<ASMLibraryRow>) { const [search, setSearch] = useState(''); const filtered = rows.filter((row) => `${row.code} ${row.milestone} ${row.wf_course}`.toLowerCase().includes(search.toLowerCase())); return <GovernanceTable title="ASM library" subtitle="Maintain the milestone standard and its associated assessment rubric." search={search} setSearch={setSearch} filters="All statuses" isLoading={isLoading} headers={['Code', 'Milestone', 'Month', 'WF course', 'Rubric focus', 'Credits', 'Status', 'Actions']} rows={filtered.map((row) => <tr key={row.id}><td className="font-mono font-bold text-emerald-700">{row.code}</td><td className="font-bold text-slate-800">{row.milestone}</td><td>{row.month}</td><td>{row.wf_course}</td><td className="max-w-[220px] text-slate-500">{row.rubric_focus}</td><td className="font-semibold">{row.credits}</td><td><StatusBadge status={row.status} /></td><td><ActionButtons actions={row.status === 'LIVE' ? [['Edit', 'edit'], ['Deactivate', 'deactivate']] : [['Edit', 'edit'], ['Activate', 'activate']]} onAction={(action) => onAction('asm-library', row.id, action)} /></td></tr>)} empty="No ASM library entries match this search." /> }
function WaiverRequests({ rows, isLoading, onAction }: TableProps<GovernanceWaiver>) { const [search, setSearch] = useState(''); const [selected, setSelected] = useState<string | null>(null); const filtered = rows.filter((row) => `${row.associate} ${row.course} ${row.milestone}`.toLowerCase().includes(search.toLowerCase())); return <><GovernanceTable title="Waiver requests" subtitle="Make controlled, auditable decisions on accelerated course progression." search={search} setSearch={setSearch} filters="Pending only" isLoading={isLoading} headers={['Associate', 'Course', 'Milestone', 'Mentor recommendation', 'System reason', 'Status', 'Decision']} rows={filtered.map((row) => <tr key={row.id}><td><div className="font-bold text-slate-800">{row.associate}</div><div className="mt-1 text-[10px] text-slate-400">Request {row.id}</div></td><td className="font-semibold text-slate-700">{row.course}</td><td>{row.milestone}</td><td>{row.mentor_recommendation}</td><td className="max-w-[240px] text-slate-500">{row.system_reason}</td><td><StatusBadge status={row.status} /></td><td><div className="flex flex-wrap gap-1.5">{row.status === 'PENDING' && <><button onClick={() => onAction('waivers', row.id, 'approve')} className="rounded border border-emerald-200 bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700 hover:bg-emerald-100">Approve</button><button onClick={() => onAction('waivers', row.id, 'reject')} className="rounded border border-red-200 bg-red-50 px-2 py-1 text-[10px] font-bold text-red-700 hover:bg-red-100">Reject</button></>}<button onClick={() => setSelected(selected === row.id ? null : row.id)} className="rounded border border-slate-200 px-2 py-1 text-[10px] font-bold text-slate-600 hover:bg-slate-50">{selected === row.id ? 'Close' : 'More info'}</button></div>{selected === row.id && <div className="mt-2 w-64 rounded border border-slate-200 bg-slate-50 p-2 text-[10px] leading-4 text-slate-500">{row.history.map((event) => <div key={event.date} className="border-b border-slate-200 py-1 last:border-0"><b>{event.label}</b> · {event.detail}</div>)}</div>}</td></tr>)} empty="No waiver requests match this search." /></> }
function DifficultyEngine({ rows, isLoading, onAction }: TableProps<DifficultyRow>) { const [search, setSearch] = useState(''); const filtered = rows.filter((row) => `${row.course} ${row.tier} ${row.difficulty}`.toLowerCase().includes(search.toLowerCase())); return <GovernanceTable title="Difficulty engine" subtitle="Use cohort evidence to keep assessment difficulty calibrated." search={search} setSearch={setSearch} filters="All classifications" isLoading={isLoading} headers={['Course', 'Tier', 'Average score', 'Pass rate', 'Difficulty', 'Calibration', 'Control']} rows={filtered.map((row) => <tr key={row.id}><td className="font-bold text-slate-800">{row.course}</td><td><TierBadge tier={row.tier} /></td><td className="font-semibold">{row.average_score}%</td><td><ValueBar value={row.pass_rate} /></td><td><DifficultyBadge difficulty={row.difficulty} /></td><td><div className="flex items-center gap-2"><input aria-label={`Calibration for ${row.course}`} type="range" min="-10" max="10" defaultValue={row.calibration} className="accent-emerald-600" /><span className="w-8 text-right text-[10px] font-bold text-slate-600">{row.calibration > 0 ? '+' : ''}{row.calibration}</span></div></td><td><button onClick={() => onAction('difficulty', row.id, 'calibrate')} className="rounded border border-slate-200 px-2.5 py-1.5 text-[10px] font-bold text-slate-700 hover:border-emerald-300 hover:text-emerald-700">Apply calibration</button></td></tr>)} empty="No difficulty records match this search." /> }
function LedgerAudit({ rows, isLoading }: { rows: LedgerAuditRow[]; isLoading: boolean }) { const [search, setSearch] = useState(''); const [sort, setSort] = useState<{ key: keyof LedgerAuditRow; direction: SortDirection }>({ key: 'date', direction: 'desc' }); const filtered = rows.filter((row) => Object.values(row).join(' ').toLowerCase().includes(search.toLowerCase())).sort((a, b) => { const left = String(a[sort.key]); const right = String(b[sort.key]); return left.localeCompare(right) * (sort.direction === 'asc' ? 1 : -1) }); const toggleSort = (key: keyof LedgerAuditRow) => setSort((current) => ({ key, direction: current.key === key && current.direction === 'asc' ? 'desc' : 'asc' })); return <GovernanceTable title="Enterprise Credit Ledger — All Associates" subtitle="Read-only audit view of credits awarded across the ASCEND program." search={search} setSearch={setSearch} filters="All domains" isLoading={isLoading} headers={['Associate', 'Date', 'Domain', 'Instrument', 'Level', 'Credits', 'Source', 'Status']} sortHeaders={['Associate', 'Date', 'Domain', 'Instrument', 'Level', 'Credits', 'Source', 'Status']} onSort={toggleSort} rows={filtered.map((row) => <tr key={row.id}><td className="font-bold text-slate-800">{row.associate}</td><td className="whitespace-nowrap text-slate-500">{row.date}</td><td><span className="rounded bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-600">{row.domain}</span></td><td>{row.instrument}</td><td>{row.level}</td><td className="font-bold text-emerald-700">+{row.credits}</td><td className="text-slate-500">{row.source}</td><td><StatusBadge status={row.status} /></td></tr>)} empty="No ledger entries match this search." /> }

type TableProps<T> = { rows: T[]; isLoading: boolean; onAction: (area: string, id: string, action: string) => Promise<void> }
function GovernanceTable({ title, subtitle, search, setSearch, filters, headers, sortHeaders, onSort, rows, empty, isLoading }: { title: string; subtitle: string; search: string; setSearch: (value: string) => void; filters: string; headers: string[]; sortHeaders?: string[]; onSort?: (key: keyof LedgerAuditRow) => void; rows: React.ReactNode[]; empty: string; isLoading: boolean }) { return <Card className="overflow-hidden"><div className="border-b border-slate-100 px-5 py-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-sm font-bold text-slate-900">{title}</h2><p className="mt-1 text-xs text-slate-400">{subtitle}</p></div><div className="flex flex-wrap gap-2"><div className="relative"><Search size={14} className="absolute left-3 top-2.5 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search records" className="h-9 w-56 rounded border border-slate-200 pl-9 pr-3 text-xs outline-none focus:border-emerald-400" /></div><button className="inline-flex h-9 items-center gap-2 rounded border border-slate-200 px-3 text-xs font-semibold text-slate-600 hover:bg-slate-50"><Filter size={14} />{filters}<ChevronDown size={13} /></button><button className="inline-flex h-9 items-center gap-2 rounded border border-slate-200 px-3 text-xs font-semibold text-slate-600 hover:bg-slate-50"><SlidersHorizontal size={14} />Columns</button></div></div></div><div className="overflow-x-auto"><table className="min-w-[980px] w-full text-left text-xs"><thead className="sticky top-0 z-10 bg-slate-50 text-[10px] uppercase tracking-[0.12em] text-slate-500"><tr>{headers.map((header, index) => <th key={header} className="whitespace-nowrap border-b border-slate-200 px-5 py-3 font-bold">{onSort && sortHeaders?.[index] === header ? <button onClick={() => onSort(header.toLowerCase().replace(/ /g, '_') as keyof LedgerAuditRow)} className="inline-flex items-center gap-1">{header}<ChevronUp size={12} /></button> : header}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{isLoading ? Array.from({ length: 4 }).map((_, index) => <tr key={index}>{headers.map((header) => <td key={header} className="px-5 py-4"><Skeleton className="h-4 w-20" /></td>)}</tr>) : rows.length ? rows : <tr><td colSpan={headers.length} className="px-5 py-12 text-center text-xs text-slate-400">{empty}</td></tr>}</tbody></table></div><div className="flex items-center justify-between border-t border-slate-100 bg-slate-50 px-5 py-3 text-[10px] text-slate-400"><span>Showing {rows.length} records</span><span className="flex items-center gap-1"><ShieldCheck size={12} className="text-emerald-600" />Read-only governance controls</span></div></Card> }
function MetricCard({ label, value, detail, icon: Icon, tone }: { label: string; value: string | number; detail: string; icon: typeof Users; tone: string }) { const tones: Record<string, string> = { blue: 'bg-blue-50 text-blue-700', emerald: 'bg-emerald-50 text-emerald-700', teal: 'bg-teal-50 text-teal-700', amber: 'bg-amber-50 text-amber-700', orange: 'bg-orange-50 text-orange-700', navy: 'bg-slate-100 text-slate-700' }; return <Card className="p-4"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">{label}</p><p className="mt-2 text-2xl font-bold tracking-tight text-slate-950">{value}</p><p className="mt-1 text-[11px] text-slate-500">{detail}</p></div><div className={`flex h-9 w-9 items-center justify-center rounded-md ${tones[tone]}`}><Icon size={17} /></div></div></Card> }
function SectionHeader({ title, subtitle, action, onClick }: { title: string; subtitle: string; action: string; onClick: () => void }) { return <div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="text-sm font-bold text-slate-900">{title}</h2><p className="mt-1 text-[11px] text-slate-400">{subtitle}</p></div><button onClick={onClick} className="hidden items-center gap-1 text-[11px] font-bold text-emerald-700 hover:text-emerald-800 sm:flex">{action}<ArrowUpRight size={13} /></button></div> }
function DecisionCard({ title, value, detail, action, onClick }: { title: string; value: string; detail: string; action: string; onClick: () => void }) { return <Card className="p-5"><div className="flex items-center justify-between"><p className="text-xs font-bold text-slate-800">{title}</p><Sparkles size={15} className="text-emerald-600" /></div><p className="mt-4 text-xl font-bold text-slate-950">{value}</p><p className="mt-1 text-[11px] leading-5 text-slate-500">{detail}</p><button onClick={onClick} className="mt-4 text-[11px] font-bold text-emerald-700 hover:text-emerald-800">{action} <ArrowUpRight size={12} className="inline" /></button></Card> }
function ValueBar({ value }: { value: number }) { return <div className="flex min-w-[90px] items-center gap-2"><ProgressBar value={value / 100} color={value >= 80 ? 'bg-emerald-500' : 'bg-amber-500'} className="w-16" /><span className="text-[11px] font-bold text-slate-700">{value}%</span></div> }
function StatusBadge({ status }: { status: GovernanceStatus | string }) { const styles: Record<string, string> = { LIVE: 'bg-emerald-50 text-emerald-700', DRAFT: 'bg-slate-100 text-slate-600', DEACTIVATED: 'bg-red-50 text-red-700', PENDING: 'bg-amber-50 text-amber-700', APPROVED: 'bg-emerald-50 text-emerald-700', REJECTED: 'bg-red-50 text-red-700', MORE_INFO: 'bg-blue-50 text-blue-700' }; return <Badge className={styles[status] || 'bg-slate-100 text-slate-600'}>{status.replace(/_/g, ' ')}</Badge> }
function TierBadge({ tier }: { tier: Tier }) { return <span className="rounded bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-600">{tier}</span> }
function DifficultyBadge({ difficulty }: { difficulty: DifficultyClass }) { const styles: Record<DifficultyClass, string> = { 'Too Easy': 'bg-blue-50 text-blue-700', Balanced: 'bg-emerald-50 text-emerald-700', 'Too Difficult': 'bg-amber-50 text-amber-700' }; return <Badge className={styles[difficulty]}>{difficulty}</Badge> }
function ActionButtons({ actions, onAction }: { actions: [string, string][]; onAction: (action: string) => void }) { return <div className="flex flex-wrap gap-1.5">{actions.map(([label, action]) => <button key={action} onClick={() => onAction(action)} className="rounded border border-slate-200 px-2 py-1 text-[10px] font-bold text-slate-600 hover:border-emerald-300 hover:text-emerald-700">{label}</button>)}</div> }
