import { motion } from 'framer-motion'
import { ArrowUpRight, CalendarDays, Check, ChevronRight, CircleAlert, Clock3, GitBranch, Layers as Layers3, MoveHorizontal as MoreHorizontal, Play, ShieldCheck, Sparkles, Target, UserRound } from 'lucide-react'
import type { DashboardData, MilestoneStatus, NextAction } from '../types'
import { Badge, Button, Card, ProgressBar, Skeleton } from '../components/ui'
import { percent } from '../lib/utils'

const statusStyles: Record<MilestoneStatus, { dot: string; text: string; bg: string; label: string }> = {
  COMPLETED: { dot: 'bg-emerald-500', text: 'text-emerald-700', bg: 'bg-emerald-50', label: 'Completed' },
  CURRENT: { dot: 'bg-blue-500', text: 'text-blue-700', bg: 'bg-blue-50', label: 'Current' },
  UPCOMING: { dot: 'bg-slate-300', text: 'text-slate-500', bg: 'bg-slate-50', label: 'Upcoming' },
  AT_RISK: { dot: 'bg-amber-500', text: 'text-amber-700', bg: 'bg-amber-50', label: 'At risk' },
  BLOCKED: { dot: 'bg-red-500', text: 'text-red-700', bg: 'bg-red-50', label: 'Blocked' },
}

export function Dashboard({ data, isLoading }: { data?: DashboardData; isLoading: boolean }) {
  if (isLoading || !data) return <DashboardSkeleton />
  const { associate, pathway } = data
  const currentMilestone = data.next_milestone
  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs font-medium text-slate-400"><span>My Dashboard</span><span>/</span><span className="text-blue-600">{associate.cohort} Cohort</span></div><h1 className="text-2xl font-bold tracking-tight text-slate-950 md:text-3xl">Good morning, {associate.name.split(' ')[0]}</h1><p className="mt-1 text-sm text-slate-500">Here’s your development overview for August 2025.</p></div><div className="flex items-center gap-2"><Button variant="outline"><CalendarDays size={15} />View calendar</Button><Button><Play size={14} fill="currentColor" />Continue journey</Button></div></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric label="Overall progress" value={percent(data.overall_progress)} detail="Across your 24-month pathway" icon={<Layers3 size={17} />} color="blue" /><Metric label="Current pathway" value={pathway.code} detail={pathway.name} icon={<GitBranch size={17} />} color="navy" /><Metric label="Credits earned" value={`${data.credits_earned} / ${data.credits_target}`} detail={`${data.credits_target - data.credits_earned} credits to target`} icon={<Sparkles size={17} />} color="amber" /><Metric label="Readiness" value={percent(data.readiness)} detail={associate.standing === 'FAST_TRACK' ? 'Fast-track trajectory' : 'On-track trajectory'} icon={<ShieldCheck size={17} />} color="emerald" /></div>
    <div className="grid gap-6 xl:grid-cols-[1.6fr_1fr]"><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="text-sm font-bold text-slate-900">24-month progression</h2><p className="mt-0.5 text-xs text-slate-400">Your pathway from foundation to architect board</p></div><div className="flex items-center gap-3 text-[10px] font-semibold text-slate-500"><Legend color="bg-emerald-500" label="Completed" /><Legend color="bg-blue-500" label="Current" /><Legend color="bg-slate-300" label="Upcoming" /></div></div><div className="p-5"><div className="mb-6 flex items-center justify-between"><div><p className="text-xs font-semibold text-slate-500">Month {data.current_month} of 24</p><p className="mt-1 text-2xl font-bold text-slate-950">{percent(data.overall_progress)} <span className="text-xs font-medium text-emerald-600">+8.4% this month</span></p></div><Badge className="bg-blue-50 text-blue-700">{associate.standing.replace('_', ' ')}</Badge></div><ProgressBar value={data.overall_progress} className="mb-7 h-2" />
    <div className="relative"><div className="grid grid-cols-12 gap-x-1 gap-y-4 sm:grid-cols-24">{data.month_progress.map((month) => { const style = statusStyles[month.status]; return <div key={month.month} className="group relative flex flex-col items-center gap-2"><div className={`flex h-8 w-full items-center justify-center rounded-sm border text-[10px] font-bold transition-transform group-hover:-translate-y-0.5 ${month.status === 'COMPLETED' ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : month.status === 'CURRENT' ? 'border-blue-500 bg-blue-600 text-white shadow-md shadow-blue-200' : month.status === 'AT_RISK' ? 'border-amber-200 bg-amber-50 text-amber-700' : month.status === 'BLOCKED' ? 'border-red-200 bg-red-50 text-red-700' : 'border-slate-200 bg-slate-50 text-slate-400'}`}>{month.milestone || month.month}</div><span className="text-[9px] font-medium text-slate-400">{month.label}</span>{month.milestone && <div className="absolute -top-8 z-10 hidden whitespace-nowrap rounded bg-slate-900 px-2 py-1 text-[9px] text-white group-hover:block">{month.milestone}</div>}<span className={`h-1.5 w-1.5 rounded-full ${style.dot}`} /></div> })}</div></div>
    <div className="mt-7 grid gap-3 border-t border-slate-100 pt-4 sm:grid-cols-3"><div><p className="text-[10px] uppercase tracking-wider text-slate-400">Current phase</p><p className="mt-1 text-xs font-bold text-slate-800">Foundation → Integration</p></div><div><p className="text-[10px] uppercase tracking-wider text-slate-400">Next milestone</p><p className="mt-1 text-xs font-bold text-slate-800">{currentMilestone?.code || 'TBD'} · {currentMilestone?.title || 'Review pathway'}</p></div><div><p className="text-[10px] uppercase tracking-wider text-slate-400">Target completion</p><p className="mt-1 text-xs font-bold text-slate-800">January 2027</p></div></div></div></Card>
    <Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="text-sm font-bold text-slate-900">Current standing</h2><p className="mt-0.5 text-xs text-slate-400">Signals across your development journey</p></div><MoreHorizontal size={18} className="text-slate-400" /></div><div className="space-y-4 p-5"><div className="flex items-center gap-3 rounded-md border border-blue-100 bg-blue-50/60 p-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-blue-100 text-blue-600"><ArrowUpRight size={18} /></div><div><p className="text-xs font-bold text-slate-800">Fast-track trajectory</p><p className="mt-0.5 text-[11px] text-slate-500">Ahead of cohort median by 12%</p></div></div><Signal label="Assessment confidence" value={data.assessment_progress} color="bg-emerald-500" /><Signal label="Milestone momentum" value={data.asm_progress} color="bg-blue-500" /><Signal label="Mentor engagement" value={0.82} color="bg-amber-500" /><div className="border-t border-slate-100 pt-4"><div className="flex items-center justify-between"><p className="text-[10px] uppercase tracking-wider text-slate-400">Next review</p><p className="text-xs font-semibold text-slate-800">Aug 28, 2025</p></div><div className="mt-2 flex items-center gap-2 text-[11px] text-slate-500"><UserRound size={13} /> With {associate.mentor_name}</div></div></div></Card></div>
    <div className="grid gap-6 xl:grid-cols-[1.2fr_1fr]"><Card><SectionHeading title="Next actions" subtitle="Prioritized steps to keep your journey moving" action="View all actions" />{data.next_actions.length === 0 ? <EmptyState text="No actions assigned" /> : <div className="divide-y divide-slate-100">{data.next_actions.map((action, i) => <ActionRow key={action.id} action={action} index={i} />)}</div>}</Card><Card><SectionHeading title="My progress" subtitle="Progress across your development pillars" /><div className="space-y-5 px-5 pb-5">{data.progress_segments.map((segment) => <div key={segment.label}><div className="mb-2 flex items-center justify-between"><div className="flex items-center gap-2"><span className="text-xs font-semibold text-slate-700">{segment.label}</span>{segment.status === 'COMPLETED' && <Check size={13} className="text-emerald-500" />}</div><span className="text-[11px] font-bold text-slate-500">{segment.value} <span className="font-normal text-slate-400">/ {segment.target}</span></span></div><ProgressBar value={segment.value / segment.target} color={segment.status === 'COMPLETED' ? 'bg-emerald-500' : 'bg-blue-600'} /></div>)}</div></Card></div>

    {/* Skills Intelligence Spotlight Banner */}
    <Card className="p-6 bg-gradient-to-r from-sky-50/80 via-indigo-50/40 to-white border-sky-200/90 shadow-2xs flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
      <div className="flex items-center gap-3.5">
        <div className="p-3 rounded-xl bg-white text-[#007df0] border border-sky-200 shadow-2xs">
          <Sparkles className="w-6 h-6 text-[#007df0]" />
        </div>
        <div>
          <div className="flex items-center gap-2 mb-0.5">
            <span className="px-2 py-0.5 text-[10px] font-bold rounded bg-sky-100 text-sky-800 uppercase">
              Skills Intelligence
            </span>
            <span className="text-xs text-slate-500 font-medium">10 Tracked Skills across 5 Enterprise Domains</span>
          </div>
          <h3 className="text-base font-bold text-slate-900">Java Concurrency (62% vs Target 80%) &amp; Kafka Streaming gaps identified</h3>
          <p className="text-xs text-slate-500 mt-0.5">
            Targeting these 2 high-priority competencies will boost your pathway readiness by +8.5%.
          </p>
        </div>
      </div>
      <a
        href="/my-skills"
        className="px-4 py-2 text-xs font-bold rounded-xl bg-[#007df0] hover:bg-[#0069cc] text-white transition shadow-xs flex items-center gap-1.5 shrink-0"
      >
        <span>Open My Skills &amp; Evidence</span>
        <ChevronRight className="w-4 h-4" />
      </a>
    </Card>

    <Card><SectionHeading title="Recent credit activity" subtitle="A transparent record of your earned credits" action="Open credit ledger" /><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-left text-xs"><thead className="border-b border-slate-100 bg-slate-50/60 text-[10px] uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3 font-semibold">Activity</th><th className="px-5 py-3 font-semibold">Source</th><th className="px-5 py-3 font-semibold">Date</th><th className="px-5 py-3 text-right font-semibold">Credits</th><th className="px-5 py-3 text-right font-semibold">Balance</th></tr></thead><tbody className="divide-y divide-slate-100">{data.recent_credits.map((credit) => <tr key={credit.id} className="transition-colors hover:bg-slate-50"><td className="px-5 py-3.5 font-semibold text-slate-800">{credit.description}</td><td className="px-5 py-3.5 text-slate-500">{credit.source}</td><td className="px-5 py-3.5 text-slate-500">{new Date(credit.awarded_at).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}</td><td className="px-5 py-3.5 text-right font-bold text-emerald-600">+{credit.amount}</td><td className="px-5 py-3.5 text-right font-semibold text-slate-700">{credit.balance_after}</td></tr>)}</tbody></table></div></Card>
  </div>
}

function Metric({ label, value, detail, icon, color }: { label: string; value: string; detail: string; icon: React.ReactNode; color: string }) { const colors: Record<string, string> = { blue: 'bg-blue-50 text-blue-600', navy: 'bg-slate-100 text-slate-700', amber: 'bg-amber-50 text-amber-600', emerald: 'bg-emerald-50 text-emerald-600' }; return <Card className="p-4 transition-shadow hover:shadow-md"><div className="flex items-start justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-xl font-bold tracking-tight text-slate-950">{value}</p><p className="mt-1 truncate text-[11px] text-slate-500">{detail}</p></div><div className={`flex h-8 w-8 items-center justify-center rounded-md ${colors[color]}`}>{icon}</div></div></Card> }
function Signal({ label, value, color }: { label: string; value: number; color: string }) { return <div><div className="mb-1.5 flex justify-between text-[11px]"><span className="font-medium text-slate-600">{label}</span><span className="font-bold text-slate-800">{percent(value)}</span></div><ProgressBar value={value} color={color} /></div> }
function Legend({ color, label }: { color: string; label: string }) { return <span className="flex items-center gap-1.5"><span className={`h-1.5 w-1.5 rounded-full ${color}`} />{label}</span> }
function SectionHeading({ title, subtitle, action }: { title: string; subtitle: string; action?: string }) { return <div className="flex items-start justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="text-sm font-bold text-slate-900">{title}</h2><p className="mt-0.5 text-xs text-slate-400">{subtitle}</p></div>{action && <button className="flex items-center gap-1 text-[11px] font-semibold text-blue-600 hover:text-blue-700">{action}<ChevronRight size={13} /></button>}</div> }
function ActionRow({ action, index }: { action: NextAction; index: number }) { const icon = action.kind === 'assessment' ? <Target size={15} /> : action.kind === 'milestone' ? <GitBranch size={15} /> : action.kind === 'mentor' ? <UserRound size={15} /> : <RouteIcon />; return <motion.div initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * 0.04 }} className="group flex items-center gap-3 px-5 py-3.5 transition-colors hover:bg-slate-50"><div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-md ${action.priority === 'HIGH' ? 'bg-blue-50 text-blue-600' : 'bg-slate-100 text-slate-500'}`}>{icon}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold text-slate-800">{action.title}</p><p className="mt-0.5 truncate text-[11px] text-slate-500">{action.detail}</p></div><div className="hidden shrink-0 text-right sm:block"><p className={`text-[10px] font-bold ${action.priority === 'HIGH' ? 'text-amber-600' : 'text-slate-400'}`}>{action.priority}</p><p className="mt-0.5 flex items-center justify-end gap-1 text-[10px] text-slate-400"><Clock3 size={10} />{action.due}</p></div><ChevronRight size={15} className="text-slate-300 transition-transform group-hover:translate-x-0.5 group-hover:text-slate-500" /></motion.div> }
function RouteIcon() { return <GitBranch size={15} /> }
function EmptyState({ text }: { text: string }) { return <div className="flex flex-col items-center justify-center px-5 py-12 text-center"><CircleAlert size={24} className="text-slate-300" /><p className="mt-2 text-sm font-medium text-slate-500">{text}</p></div> }
function DashboardSkeleton() { return <div className="space-y-6"><div><Skeleton className="h-3 w-28" /><Skeleton className="mt-3 h-8 w-72" /><Skeleton className="mt-2 h-4 w-80" /></div><div className="grid gap-4 md:grid-cols-4">{[1, 2, 3, 4].map((i) => <Skeleton key={i} className="h-28" />)}</div><div className="grid gap-6 xl:grid-cols-[1.6fr_1fr]"><Skeleton className="h-[410px]" /><Skeleton className="h-[410px]" /></div></div> }
