from __future__ import annotations

from typing import List, Dict, Any
from app.models.schemas import MarketplaceProject, MarketplaceApplication

DEFAULT_MARKETPLACE_PROJECTS: List[MarketplaceProject] = [
    MarketplaceProject(
        id="gig-101",
        title="High-Throughput Kafka Outbox Partitioning & Sharding",
        business_unit="Enterprise Payments & Settlement",
        team="Real-Time Clearing Squad",
        technical_stack=["Java 21", "Kafka", "PostgreSQL", "Kubernetes", "Distributed Systems"],
        target_competency_tier="L400",
        allocation_percentage=50,
        duration_weeks=8,
        mentorship_available=True,
        business_impact="Eliminates cross-partition head-of-line blocking for $1.2B daily high-value clearing volume.",
        open_seats=2,
        status="OPEN",
        posted_by="Priya Nair (Principal Architect)",
        created_at="2026-08-20",
    ),
    MarketplaceProject(
        id="gig-102",
        title="RAG Semantic Caching & Bedrock Embedding Gateway",
        business_unit="Enterprise AI Innovation Hub",
        team="Generative AI Platform",
        technical_stack=["Python", "LangChain", "pgvector", "AWS Bedrock", "FastAPI"],
        target_competency_tier="L300",
        allocation_percentage=100,
        duration_weeks=6,
        mentorship_available=True,
        business_impact="Reduces LLM inference latency by 65% across 40+ internal AI assistants.",
        open_seats=1,
        status="OPEN",
        posted_by="Vikram Desai (AI Engineering Director)",
        created_at="2026-08-22",
    ),
    MarketplaceProject(
        id="gig-103",
        title="Multi-Cloud Zero-Trust Mesh Policy Engine",
        business_unit="Global Infrastructure & Cloud",
        team="Platform Security Engineering",
        technical_stack=["Go", "Istio", "Open Policy Agent (OPA)", "Terraform", "AWS"],
        target_competency_tier="L300",
        allocation_percentage=50,
        duration_weeks=10,
        mentorship_available=True,
        business_impact="Enforces uniform mTLS and dynamic RBAC policies across AWS and GCP multi-region clusters.",
        open_seats=2,
        status="OPEN",
        posted_by="Suresh Pillai (Security Architect)",
        created_at="2026-08-18",
    ),
    MarketplaceProject(
        id="gig-104",
        title="Event-Driven Core Ledger Reconciliation Pipeline",
        business_unit="Core Banking Modernization",
        team="Ledger & Balance Squad",
        technical_stack=["Java 21", "Spring Boot", "Kafka", "PostgreSQL", "Docker"],
        target_competency_tier="L200",
        allocation_percentage=50,
        duration_weeks=4,
        mentorship_available=True,
        business_impact="Automates T+0 end-of-day ledger reconciliation across 12 banking entities.",
        open_seats=3,
        status="OPEN",
        posted_by="Anand Verma (Engineering Manager)",
        created_at="2026-08-25",
    ),
]

DEFAULT_MARKETPLACE_APPLICATIONS: List[MarketplaceApplication] = [
    MarketplaceApplication(
        id="app-101",
        project_id="gig-101",
        project_title="High-Throughput Kafka Outbox Partitioning & Sharding",
        associate_id="as-ananya",
        associate_name="Ananya Rao",
        pathway="Software Engineering (SE)",
        match_score=94.5,
        match_breakdown={
            "Skill Overlap (40%)": 38.0,
            "Pathway Alignment (20%)": 20.0,
            "Capacity & Allocation (15%)": 14.0,
            "Readiness Rating (15%)": 13.5,
            "Growth Opportunity (10%)": 9.0,
        },
        candidate_pitch="Strong alignment with my ASM-104 capstone on transactional outbox patterns. Recently verified at L400 Distributed Systems by the Architect Board.",
        status="SHORTLISTED",
        applied_at="2026-08-26 10:15",
    ),
    MarketplaceApplication(
        id="app-102",
        project_id="gig-102",
        project_title="RAG Semantic Caching & Bedrock Embedding Gateway",
        associate_id="as-rohan",
        associate_name="Rohan Mehta",
        pathway="AI Engineering (AIE)",
        match_score=91.0,
        match_breakdown={
            "Skill Overlap (40%)": 36.5,
            "Pathway Alignment (20%)": 19.5,
            "Capacity & Allocation (15%)": 14.0,
            "Readiness Rating (15%)": 12.5,
            "Growth Opportunity (10%)": 8.5,
        },
        candidate_pitch="Authored ASM-103 pgvector similarity pipeline with 98.4% top-k recall. Ready for 100% full-time commitment on RAG optimization.",
        status="INTERVIEW_SCHEDULED",
        applied_at="2026-08-25 14:30",
    ),
]
