from __future__ import annotations

from typing import List, Dict
from app.models.schemas import (
    WorkflowNode,
    WorkflowEdge,
    WorkflowDefinition,
    WorkflowHistoryEntry,
    WorkflowInstance,
    NotificationItem,
    NotificationTemplate,
)

# ---------------------------------------------------------------------------
# Seed Workflow Definitions (Requirement 12 & 13)
# ---------------------------------------------------------------------------

DEFAULT_WORKFLOWS: List[WorkflowDefinition] = [
    WorkflowDefinition(
        id="wf-def-waiver",
        code="FAST_TRACK_WAIVER",
        name="Fast-Track & Course Waiver Approval Workflow",
        description="Sequential 3-stage governance process for approving accelerated course exemptions and fast-track pathway promotions.",
        category="WAIVER",
        version=1,
        is_active=True,
        updated_at="2026-08-25",
        nodes=[
            WorkflowNode(id="n-start", label="Waiver Request Submission", type="START", role="EARLY_TALENT", sla_hours=0, warning_hours=0, position_x=50, position_y=150),
            WorkflowNode(id="n-mentor", label="Mentor Technical Evaluation", type="REVIEW", role="MENTOR_COACH", sla_hours=48, warning_hours=24, escalation_role="ENGINEERING_EXCELLENCE_COMMITTEE", position_x=280, position_y=150),
            WorkflowNode(id="n-committee", label="Engineering Committee Governance", type="APPROVAL", role="ENGINEERING_EXCELLENCE_COMMITTEE", sla_hours=72, warning_hours=36, escalation_role="SENIOR_LEADER_SPONSOR", position_x=530, position_y=150),
            WorkflowNode(id="n-sponsor", label="Senior Sponsor Final Ratification", type="APPROVAL", role="SENIOR_LEADER_SPONSOR", sla_hours=48, warning_hours=24, escalation_role="TECHNOLOGY_HEAD", position_x=780, position_y=150),
            WorkflowNode(id="n-end", label="Waiver Executed & Credits Deposited", type="END", role="SYSTEM", sla_hours=0, warning_hours=0, position_x=1030, position_y=150),
        ],
        edges=[
            WorkflowEdge(id="e-1", source="n-start", target="n-mentor", label="Submits Evidence"),
            WorkflowEdge(id="e-2", source="n-mentor", target="n-committee", label="Recommends (SLA 48h)"),
            WorkflowEdge(id="e-3", source="n-committee", target="n-sponsor", label="Endorses (SLA 72h)"),
            WorkflowEdge(id="e-4", source="n-sponsor", target="n-end", label="Approved & Activated"),
        ],
    ),
    WorkflowDefinition(
        id="wf-def-pathway",
        code="PATHWAY_SELECTION",
        name="Tri-Party Pathway Reconciliation Workflow",
        description="Automated reconciliation between Algorithmic Recommendation, Mentor Coach Review, and Committee Decision.",
        category="PATHWAY",
        version=1,
        is_active=True,
        updated_at="2026-08-20",
        nodes=[
            WorkflowNode(id="p-start", label="Gate 1 Algorithmic Recommendation", type="START", role="SYSTEM", sla_hours=0, warning_hours=0, position_x=50, position_y=150),
            WorkflowNode(id="p-mentor", label="Mentor Pathway Endorsement", type="REVIEW", role="MENTOR_COACH", sla_hours=48, warning_hours=24, position_x=300, position_y=150),
            WorkflowNode(id="p-decision", label="Alignment Evaluation", type="CONDITION", role="SYSTEM", sla_hours=12, warning_hours=6, position_x=550, position_y=150),
            WorkflowNode(id="p-committee", label="Committee Override / Ratification", type="APPROVAL", role="ENGINEERING_EXCELLENCE_COMMITTEE", sla_hours=48, warning_hours=24, position_x=800, position_y=150),
            WorkflowNode(id="p-end", label="Pathway Enrolled", type="END", role="SYSTEM", sla_hours=0, warning_hours=0, position_x=1050, position_y=150),
        ],
        edges=[
            WorkflowEdge(id="pe-1", source="p-start", target="p-mentor", label="Generated"),
            WorkflowEdge(id="pe-2", source="p-mentor", target="p-decision", label="Mentor Input"),
            WorkflowEdge(id="pe-3", source="p-decision", target="p-committee", label="If Divergent"),
            WorkflowEdge(id="pe-4", source="p-decision", target="p-end", label="If Aligned"),
            WorkflowEdge(id="pe-5", source="p-committee", target="p-end", label="Ratified"),
        ],
    ),
    WorkflowDefinition(
        id="wf-def-defense",
        code="ARCHITECT_DEFENSE",
        name="Architect Board Defense & RFC Ratification Workflow",
        description="Multi-examiner panel evaluation and rubric scoring for ASM Capstone defenses.",
        category="ARCHITECT_BOARD",
        version=2,
        is_active=True,
        updated_at="2026-08-22",
        nodes=[
            WorkflowNode(id="ad-start", label="RFC Document Submission", type="START", role="EARLY_TALENT", sla_hours=0, warning_hours=0, position_x=50, position_y=150),
            WorkflowNode(id="ad-mentor", label="Mentor Readiness Sign-off", type="REVIEW", role="MENTOR_COACH", sla_hours=24, warning_hours=12, position_x=300, position_y=150),
            WorkflowNode(id="ad-panel", label="Architect Board Panel Defense", type="DECISION", role="ENGINEERING_EXCELLENCE_COMMITTEE", sla_hours=48, warning_hours=24, position_x=600, position_y=150),
            WorkflowNode(id="ad-end", label="Defense Passed & L4 Certified", type="END", role="SYSTEM", sla_hours=0, warning_hours=0, position_x=900, position_y=150),
        ],
        edges=[
            WorkflowEdge(id="ade-1", source="ad-start", target="ad-mentor", label="Submits RFC"),
            WorkflowEdge(id="ade-2", source="ad-mentor", target="ad-panel", label="Approved for Defense"),
            WorkflowEdge(id="ade-3", source="ad-panel", target="ad-end", label="Score >= 3.5 / 5.0"),
        ],
    ),
]


# ---------------------------------------------------------------------------
# Seed Active Workflow Instances (Requirement 12 & 14)
# ---------------------------------------------------------------------------

ACTIVE_WORKFLOW_INSTANCES: List[WorkflowInstance] = [
    WorkflowInstance(
        id="inst-101",
        workflow_id="wf-def-waiver",
        workflow_code="FAST_TRACK_WAIVER",
        workflow_name="Fast-Track & Course Waiver Approval Workflow",
        associate_id="as-ananya",
        associate_name="Ananya Rao",
        current_step_id="n-sponsor",
        current_step_name="Senior Sponsor Final Ratification",
        current_assignee_role="SENIOR_LEADER_SPONSOR",
        status="IN_REVIEW",
        created_at="2026-08-25 14:00",
        due_date="2026-08-28 14:00",
        sla_hours=48,
        sla_status="HEALTHY",
        payload={
            "waiver_type": "Fast-Track Foundational Exemption",
            "exempt_courses": "WF-101 (Java Core & AI Prompting)",
            "credits_requested": "15",
            "justification": "Candidate demonstrated 91% coding performance on concurrent idempotency challenges and published production PR #14.",
        },
        history=[
            WorkflowHistoryEntry(
                id="h-1",
                step_id="n-start",
                step_name="Waiver Request Submission",
                actor_id="as-ananya",
                actor_name="Ananya Rao",
                actor_role="EARLY_TALENT",
                action="SUBMIT",
                decision_reason="Initiated accelerated waiver request based on top 5% assessment score.",
                comments="All foundational verification test cases passed.",
                timestamp="2026-08-25 14:00",
                sla_met=True,
            ),
            WorkflowHistoryEntry(
                id="h-2",
                step_id="n-mentor",
                step_name="Mentor Technical Evaluation",
                actor_id="u-priya",
                actor_name="Priya Nair",
                actor_role="MENTOR_COACH",
                action="APPROVE",
                decision_reason="Candidate code meets senior architectural standards.",
                comments="Strongly endorse fast-track; Ananya has proven capability in live fire testing.",
                timestamp="2026-08-26 10:30",
                sla_met=True,
            ),
            WorkflowHistoryEntry(
                id="h-3",
                step_id="n-committee",
                step_name="Engineering Committee Governance",
                actor_id="u-committee",
                actor_name="Committee Governance Board",
                actor_role="ENGINEERING_EXCELLENCE_COMMITTEE",
                action="APPROVE",
                decision_reason="Rubric calibration benchmark met with 94.2% confidence.",
                comments="Governance checks satisfied. Forwarded to VP Sponsor.",
                timestamp="2026-08-26 18:00",
                sla_met=True,
            ),
        ],
    ),
    WorkflowInstance(
        id="inst-102",
        workflow_id="wf-def-pathway",
        workflow_code="PATHWAY_SELECTION",
        workflow_name="Tri-Party Pathway Reconciliation Workflow",
        associate_id="as-fatima",
        associate_name="Fatima Sheikh",
        current_step_id="p-mentor",
        current_step_name="Mentor Pathway Endorsement",
        current_assignee_role="MENTOR_COACH",
        status="PENDING",
        created_at="2026-08-26 08:00",
        due_date="2026-08-27 18:00",
        sla_hours=48,
        sla_status="WARNING",
        payload={
            "algorithmic_recommendation": "Data Engineering (DE)",
            "score_matrix": "DE: 25, SE: 23, CSE: 23, IE: 22",
            "primary_skill": "Streaming & Spark Architecture",
        },
        history=[
            WorkflowHistoryEntry(
                id="h-4",
                step_id="p-start",
                step_name="Gate 1 Algorithmic Recommendation",
                actor_id="system",
                actor_name="ASCEND Recommendation Engine",
                actor_role="SYSTEM",
                action="SUBMIT",
                decision_reason="Gate 1 multi-domain examination completed.",
                comments="Data Engineering computed as top statistical affinity.",
                timestamp="2026-08-26 08:00",
                sla_met=True,
            ),
        ],
    ),
    WorkflowInstance(
        id="inst-103",
        workflow_id="wf-def-defense",
        workflow_code="ARCHITECT_DEFENSE",
        workflow_name="Architect Board Defense & RFC Ratification Workflow",
        associate_id="as-rohan",
        associate_name="Rohan Mehta",
        current_step_id="ad-panel",
        current_step_name="Architect Board Panel Defense",
        current_assignee_role="ENGINEERING_EXCELLENCE_COMMITTEE",
        status="IN_REVIEW",
        created_at="2026-08-24 09:00",
        due_date="2026-08-28 17:00",
        sla_hours=72,
        sla_status="HEALTHY",
        payload={
            "rfc_title": "Real-Time Payments Partitioning & Vector Cache RFC",
            "stream": "STREAM 04/05",
            "panel_members": "Priya Nair, Vikram Desai, Suresh Pillai",
        },
        history=[
            WorkflowHistoryEntry(
                id="h-5",
                step_id="ad-start",
                step_name="RFC Document Submission",
                actor_id="as-rohan",
                actor_name="Rohan Mehta",
                actor_role="EARLY_TALENT",
                action="SUBMIT",
                decision_reason="Completed ASM-103 and submitted RFC documentation.",
                comments="All architecture constraints addressed in design doc.",
                timestamp="2026-08-24 09:00",
                sla_met=True,
            ),
            WorkflowHistoryEntry(
                id="h-6",
                step_id="ad-mentor",
                step_name="Mentor Readiness Sign-off",
                actor_id="u-priya",
                actor_name="Priya Nair",
                actor_role="MENTOR_COACH",
                action="APPROVE",
                decision_reason="Candidate RFC is production grade.",
                comments="Cleared for board defense.",
                timestamp="2026-08-25 11:00",
                sla_met=True,
            ),
        ],
    ),
]


# ---------------------------------------------------------------------------
# Seed Enterprise Notification Center (Requirement 15)
# ---------------------------------------------------------------------------

DEFAULT_NOTIFICATIONS: List[NotificationItem] = [
    NotificationItem(
        id="notif-1",
        user_id="u-sponsor",
        title="Approval Required: Fast-Track Waiver (Ananya Rao)",
        message="Ananya Rao has received Mentor and Committee endorsements for Fast-Track Foundational Waiver. Your executive sign-off is required within 18h.",
        channel="IN_APP",
        event_type="APPROVAL_REQUIRED",
        is_read=False,
        urgency="WARNING",
        created_at="2 hours ago",
        action_url="/sponsor?view=approvals",
        metadata={"instance_id": "inst-101", "associate": "Ananya Rao"},
    ),
    NotificationItem(
        id="notif-2",
        user_id="u-priya",
        title="SLA Warning: Pathway Endorsement Approaching Deadline",
        message="Fatima Sheikh's Data Engineering pathway selection is approaching its 48h SLA threshold (4 hours remaining).",
        channel="TEAMS",
        event_type="WORKFLOW_ESCALATION",
        is_read=False,
        urgency="CRITICAL",
        created_at="1 hour ago",
        action_url="/mentor?view=pathway",
        metadata={"instance_id": "inst-102", "associate": "Fatima Sheikh"},
    ),
    NotificationItem(
        id="notif-3",
        user_id="as-ananya",
        title="Personalized Learning Recommendation Generated",
        message="AI Engine identified a Kafka streaming competency gap (-18.0 pts) and assigned Challenge CC-103.",
        channel="IN_APP",
        event_type="SKILL_GAP_IDENTIFIED",
        is_read=True,
        urgency="NORMAL",
        created_at="4 hours ago",
        action_url="/my-skills",
        metadata={"skill": "Apache Kafka"},
    ),
    NotificationItem(
        id="notif-4",
        user_id="as-ananya",
        title="Credits Awarded: +15 Credits for ASM Pipeline PR",
        message="Your pull request for high-throughput pipeline configuration was verified and merged into staging.",
        channel="SLACK",
        event_type="APPROVAL_COMPLETED",
        is_read=True,
        urgency="NORMAL",
        created_at="Yesterday",
        action_url="/credit-ledger",
        metadata={"credits": "15"},
    ),
]

NOTIFICATION_TEMPLATES: List[NotificationTemplate] = [
    NotificationTemplate(
        id="tpl-approval-req",
        event_type="APPROVAL_REQUIRED",
        name="Executive Approval Required",
        subject_template="[ASCEND] Action Required: {{workflow_name}} for {{associate_name}}",
        body_template="A new approval request has been escalated to your queue with SLA of {{sla_hours}} hours. Please review justification and render a decision.",
        default_channels=["IN_APP", "TEAMS", "EMAIL"],
    ),
    NotificationTemplate(
        id="tpl-sla-breach",
        event_type="WORKFLOW_ESCALATION",
        name="SLA Warning & Escalation Alert",
        subject_template="[ASCEND CRITICAL] SLA Warning: {{workflow_name}} ({{remaining_hours}}h remaining)",
        body_template="Task has reached warning threshold without sign-off. If not completed within SLA, will automatically escalate to {{escalation_role}}.",
        default_channels=["TEAMS", "SLACK", "EMAIL"],
    ),
    NotificationTemplate(
        id="tpl-skill-gap",
        event_type="SKILL_GAP_IDENTIFIED",
        name="Competency Gap Identified",
        subject_template="[ASCEND AI] Skill Gap Alert: {{skill_name}} (Delta: {{gap_points}} pts)",
        body_template="Telemetry identified a drop in {{skill_name}}. AI Coach has generated 3 targeted practice challenges to restore trajectory.",
        default_channels=["IN_APP", "EMAIL"],
    ),
]
